package echo.music.enhanced.crashlytics

import android.content.Context
import android.util.Log
import com.google.firebase.crashlytics.FirebaseCrashlytics
import echo.music.enhanced.domain.data.player.PlayerError

/**
 * Runs [block] against Crashlytics only when Firebase is actually configured.
 *
 * Firebase auto-initializes from resources generated by the google-services
 * Gradle plugin. That plugin is currently disabled (see androidApp/build.gradle.kts),
 * so no default FirebaseApp exists and [FirebaseCrashlytics.getInstance] throws.
 * Reporting degrades to logcat until this project supplies its own Firebase
 * configuration, at which point it resumes with no code change here.
 */
private inline fun withCrashlytics(block: (FirebaseCrashlytics) -> Unit) {
    try {
        block(FirebaseCrashlytics.getInstance())
    } catch (_: IllegalStateException) {
        // Firebase not configured — the log statements above are the record.
    }
}

fun reportCrash(throwable: Throwable) {
    Log.e("Crashlytics", "Crash reported: ${throwable.localizedMessage}")
    withCrashlytics { it.recordException(throwable) }
}

fun configCrashlytics(applicationContext: Context, dsn: String) {
    Log.d("Crashlytics", "Configuring crashlytics (Firebase auto-initializes, DSN ignored)")
}

fun pushPlayerError(error: PlayerError) {
    Log.e("Crashlytics", "Player Error: ${error.message}, code: ${error.errorCode}, code name: ${error.errorCodeName}")
    val exception = Exception("Player Error: ${error.message} [Code: ${error.errorCode} - ${error.errorCodeName}]")
    withCrashlytics { it.recordException(exception) }
}